services:
  frontend:
    build: .
    container_name: portfolio-frontend
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://budhilaw.com/api/v1
    networks:
      - portfolio-network

networks:
  portfolio-network:
    external: true
    name: portfolio-network 