version: '3.8'

services:
  frontend:
    build: .
    container_name: portfolio-frontend
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    networks:
      - internal
      - portfolio-network

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
    networks:
      - internal
      - portfolio-network

networks:
  internal:
    driver: bridge
  portfolio-network:
    external: true
    name: portfolio-network

volumes:
  nginx-logs: 