name: Build and Deploy Frontend

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - master
          - develop
      force_rebuild:
        description: 'Force rebuild without cache'
        required: false
        default: false
        type: boolean
      skip_build:
        description: 'Skip build step'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Setup Node.js
      if: ${{ !github.event.inputs.skip_build }}
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      if: ${{ !github.event.inputs.skip_build }}
      run: npm ci

    - name: Build application
      if: ${{ !github.event.inputs.skip_build }}
      run: npm run build

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        no-cache: ${{ github.event.inputs.force_rebuild == 'true' }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: |
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') ||
      (github.event_name == 'workflow_dispatch')
    
    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          # Set non-interactive mode for Docker
          export DOCKER_CLI_HINTS=false
          export DOCKER_BUILDKIT=1
          
          # Explicitly logout from all registries to avoid conflicts
          echo "Clearing any existing Docker logins..."
          docker logout || true
          docker logout ghcr.io || true
          docker logout docker.io || true
          
          # Use latest tag for all deployments
          IMAGE_TAG="latest"
          
          # Login to GHCR explicitly
          echo "Logging into GHCR..."
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Pull the latest image with timeout
          echo "Pulling image from GHCR: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}"
          timeout 300 docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}
          
          # Stop and remove existing container
          docker stop portfolio-frontend || true
          docker rm portfolio-frontend || true
          
          # Create network if it doesn't exist
          docker network create portfolio-network || true
          
          # Run new container
          docker run -d \
            --name portfolio-frontend \
            --restart unless-stopped \
            --network portfolio-network \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}
          
          # Verify container is running
          echo "Verifying container status..."
          docker ps | grep portfolio-frontend || echo "Container not found in running state"
          docker logs portfolio-frontend --tail 10 || echo "Could not get container logs"
          
          # Clean up old images
          docker image prune -f
          
          # Logout from GHCR
          docker logout ghcr.io

  notify:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify deployment result
      run: |
        if [ "${{ needs.deploy.result }}" = "success" ]; then
          echo "✅ Frontend deployment to production successful!"
          echo "Branch: ${{ github.event.inputs.branch || github.ref_name }}"
        else
          echo "❌ Frontend deployment failed!"
          echo "Branch: ${{ github.event.inputs.branch || github.ref_name }}"
        fi 